apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-auth
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            auth_basic  "Basic Auth";
            auth_basic_user_file /etc/apache2/.htpasswd;
          }
       }
    }

  htpasswd: |
    user1:$apr1$4PYvQUCI$0UHanoYXzzK5xx0LP4X5T0

